# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [43]:

import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
customer_data = pd.read_csv(url)
#display(customer_data).head()


display(customer_data.shape)


display(customer_data.dtypes)
#customer_data["Customer Lifetime Value"] should be a float dtype
#customer_data["number of Open Complaints"] should be an int dtype


display(customer_data.describe(include="str"))
display(customer_data.describe())
display(customer_data[["Income","Monthly Premium Auto","Total Claim Amount"]].mode())
# Series - ST, GENDER, Education, Policy Type, Vehicle Class are used for categorising the data effectively
#  Income and Total Claim Amount: mean > median, which implies the distributions are rightly skewed. But Monthly Premium Auto has Mean < median, which implies data error.
#float values can be rounded to 2 to look precise.
# The most frequent value (mode) of Income is 0, which means the data is either incomplete or the corresponding customers are unemployed

display(customer_data["GENDER"].value_counts())
# GENDER series has typo errors and should be only Male and Female categories

print("\n",customer_data["Customer"].value_counts())
#Customer_id is unique in the dataframe

print("\n",customer_data["ST"].value_counts())
#most of the customers are from the state Oregon

print("\n",customer_data["Customer Lifetime Value"].value_counts())
# wrong data type as string instead of float.There are 3 missing values. % sign is not necessary here.

(4008, 11)

Customer                         str
ST                               str
GENDER                           str
Education                        str
Customer Lifetime Value          str
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints        str
Policy Type                      str
Vehicle Class                    str
Total Claim Amount           float64
dtype: object

,Customer,ST,GENDER,Education,Customer Lifetime Value,Number of Open Complaints,Policy Type,Vehicle Class
count,1071,1071,954,1071,1068,1071,1071,1071
unique,1071,8,5,6,1027,6,3,6
top,RB50392,Oregon,F,Bachelor,445811.34%,1/0/00,Personal Auto,Four-Door Car
freq,1,320,457,324,4,830,780,576

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

   Income  Monthly Premium Auto  Total Claim Amount
0     0.0                  65.0               321.6

GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

 Customer
RB50392    1
QZ44356    1
AI49188    1
WW63253    1
GA49547    1
          ..
TM65736    1
VJ51327    1
GS98873    1
CW49887    1
MY31220    1
Name: count, Length: 1071, dtype: int64

 ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

 Customer Lifetime Value
445811.34%     4
251459.20%     4
2412750.40%    3
684615.03%     3
578018.22%     3
              ..
284226.69%     1
305955.03%     1
2031499.76%    1
323912.47%     1
899704.02%     1
Name: count, Length: 1027, dtype: int64

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [49]:
location = customer_data["ST"].value_counts().sort_values(ascending = True)
display(location.head())

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [53]:
policy_type = customer_data["Policy Type"].value_counts()
display(policy_type)
print(f"highest number of policies sold for :{policy_type.idxmax()}")

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

highest number of policies sold for Personal Auto

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [62]:

df1 = customer_data.loc[customer_data["Policy Type"]== "Personal Auto","Income"]
display(df1)
df2 = customer_data.loc[customer_data["Policy Type"]== "Corporate Auto","Income"]
display(df2)
print("Average income of customers taken Personal Auto policy:",df1.mean())
print("Average income of customers taken Corporate Auto policy:",df2.mean())

0           0.0
1           0.0
2       48767.0
4       36357.0
5       62902.0
         ...
1065    69417.0
1066    38644.0
1067    63209.0
1068    16061.0
1070    54230.0
Name: Income, Length: 780, dtype: float64

3           0.0
6       55350.0
7           0.0
8       14072.0
12      77026.0
         ...
1045    94389.0
1050    51978.0
1052    86721.0
1056    89451.0
1059    54193.0
Name: Income, Length: 234, dtype: float64

Average income of customers taken Personal Auto policy: 38180.69871794872
Average income of customers taken Corporate Auto policy: 41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*